### ISSUE TITLE
Can curl::easy  reuse？

### ISSUE THREAD

**Issue by zuowanbushiwo** [mologie/curl-asio#7]
thanks，This is a very good open source project that is very useful to me！
      I now have a need to determine whether to continue downloading body content based on the content-type of the header information of the request url . So in order to speed up the content of the downloaded body, I can use a link that has been created to get the header information。I made the following changes, but I can't get right result. Is there another way? 
                                                                                                                                                thanks！
`void handle_download_completed(const boost::system::error_code& err, std::string url, curl::easy* easy, bool isHeader);

void start_download_FollowBody(const std::string& url,curl::easy* easy)
{
	// see 'Use server-provided file names' example for a more detailed implementation of this function which receives
	// the target file name from the server using libcurl's header callbacks
	std::string file_name = url.substr(url.find_last_of('/') + 1);
	std::cerr << file_name << std::endl;
	easy->set_url(url);
	easy->set_sink(boost::make_shared<std::ofstream>(file_name.c_str(), std::ios::binary));
	bool isHeader = false;
	easy->async_perform(boost::bind(handle_download_completed, boost::asio::placeholders::error, url, easy,isHeader));
}

void handle_download_completed(const boost::system::error_code& err, std::string url, curl::easy* easy, bool isHeader)
{
    std::cout << "isHeader : " << isHeader << std::endl;
    if(isHeader && !err){
          std::string info   =  easy->get_content_type();
	      double fileLength  =  easy->get_content_length_download();
	      std::cout << "info : " << info << ", fileLength" << fileLength << std::endl;
		  if(my_need){
		    start_download_FollowBody(url,easy);
		    return;
		  } 
	}

	if (!err)
	{
		std::cout << "Download of " << url << " completed" << std::endl;
	}
	else
	{
		std::cout << "Download of " << url << " failed: " << err.message() << std::endl;
	}
	
	active_downloads.erase(*easy);
}

void start_download(curl::multi& multi, const std::string& url)
{
	std::auto_ptr<curl::easy> easy(new curl::easy(multi));
	easy->set_url(url);
	easy->set_header(true);
	easy->set_no_body(true);
	bool isHeader = true;
	easy->async_perform(boost::bind(handle_download_completed, boost::asio::placeholders::error, url, easy.get(),isHeader));
	active_downloads.insert(easy);
}`

**Comment by mologie** [comment]
Hi, this library is 4-5 years old and I'm currently not maintaining it, though it still seems to work. Do you really want to use it? With that question out of the way, on to your problem:

Please check the libcurl docs for CURLOPT_HEADER: https://curl.haxx.se/libcurl/c/CURLOPT_HEADER.html - it includes the header into the body, which is probably not what you want. Better remove that option from your config.

~~Other than that your code looks right-ish.~~ I unfortunately cannot test it because you have not provided a complete example. Can you give more details?

EDIT:

After reading the library code I think that the issue is indeed because you're reusing curl easy handles. Try creating a new handle and use that instead. You can also add both curl::easy handles to one curl::multi so that it reuses one connection.

**Comment by zuowanbushiwo** [comment]
thanks
